parameters: {}
environment: {}
packages:
    - name: health
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: status
          binary: false
          main: ""
          runtime: python:3.13
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
    - name: ocr
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: read-image
          binary: false
          main: ""
          runtime: python:3.13
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}